travis:
  secure:
    BINSTAR_TOKEN: kerI9FXPv0r6+EO7m1RZSbRVi5nWsrSUmV0f3PuFRRNU2rVmrd8f75ThSkcen56XH5NHIPo24VJ6GvQWrzrAlPtIyGNWOtBYHsZmoQ8FLWgX3yErX+v5qxJX5zAuNhbzHw5ASmT8HI1mvBWNwBYfK0rBihfWSRCO0B3G4mrt4DMRu7XcjkBPQGPl4y/dkAmNyaupzxGnICQT7TY5I/qsN2MhL2GnORhakml7J7+spL0J0GJOBvI5IQY42RjXPgIccm7PMucpRcSYE7ZZtjuNNPyy5GGdjxm7FeENXIsMYpyVBFnM4lhvNEK9wLEyzUMfiXmvgX0UtUmqhTJ2+m18fY0+syeBadurJu0dChgEKg6rPpX11QRWbf6ShxRXtCcZutqy0jsIFIPGlWJ8mnYBChYE5FYbc9L1iP7b8P/CKLfLIGMoUkMASEhabW1j86WBlE120umr4M5aEXWCxzoUC8mxOxHsPBcSFbT08LXE/TXvGhDcokIdSbrkxAATbWt8ldUyRz5y8qgGmrgbhWu0UQ5f+x680kCp4/ZDX15bg0BGKmd3eOaMNmhr8qRH69MFvlCqjWUcf5zMK8vfglbVtTJ2ybhIgyJ/gjE3j+2aYu5rhTcIeQxA8wjQTIWsqcPhp3Y4vVUVg+YZsUHmgZOYdFxRhVhjJgh1etM4vLoFYPw=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
